name: Java CI with Maven

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    branches: [ "main", "release-*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: zulu
        cache: maven

    - name: Build with Maven
      run: ./mvnw -V --no-transfer-progress -Dstyle.color=always clean verify
